language: python

python: 
   - "3.6"

script:
   - python test.py

notifications:
  email:
    recipients:
      - 1841187753@qq.com
    on_success: never # default: change
    on_failure: always # default: always

